version: build{build}

image:
  - Visual Studio 2019

clone_folder: C:\Documents\programs\MultipliMachineStudy

init:
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Set-AppveyorBuildVariable "SPECIALVERSION" ""
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }
      else
      {
        Set-AppveyorBuildVariable "SPECIALVERSION" "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))-$env:APPVEYOR_BUILD_NUMBER"
        Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))-$env:APPVEYOR_BUILD_NUMBER"
      }
  - mkdir C:\util
  - set QTDIR=C:\Qt\6.2.2\msvc2019_64
  - set "PATH=%PATH%;%QTDIR%\bin;C:\util;C:\Program Files (x86)\Inno Setup 6"
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"

install:
  - git submodule update --init --recursive
  - curl -sSL https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-win.zip > C:\util\ninja-win.zip
  - 7z e -oC:\util C:\util\ninja-win.zip

before_build:
  - cd C:\Documents\programs\MultipliMachineStudy\src
  - mkdir build-MachineStudy-Qt_6_2_2-Release

build_script:
  - cd build-MachineStudy-Qt_6_2_2-Release
  - cmake ..\MachineStudy -DCMAKE_BUILD_TYPE=RelWithDebInfo -GNinja -DSPECIALVERSION=%SPECIALVERSION% -DCMAKE_PREFIX_PATH=%QTDIR%
  - cmake --build . --target all

after_build:
  - cmake --build . --target install
  - cd install
  - iscc MachineStudy.iss

test: off

artifacts:
  - path: 'src\build-MachineStudy-Qt_6_2_2-Release\install\Output\*.exe'

