version: build{build}

image:
  - Visual Studio 2017

clone_folder: C:\Documents\programs\MultipliMachineStudy

init:
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }
      else
      {
        Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))-$env:APPVEYOR_BUILD_NUMBER"
      }
  - mkdir C:\util
  - set QTDIR=C:\Qt\5.11.1\msvc2015
  - set "PATH=%PATH%;%QTDIR%\bin;C:\util;C:\Program Files (x86)\Inno Setup 5"
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"

install:
  - git submodule update --init --recursive
  - curl -sSL https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip > C:\util\ninja-win.zip
  - 7z e -oC:\util C:\util\ninja-win.zip

before_build:
  - cd C:\Documents\programs\MultipliMachineStudy\src
  - mkdir build-MachineStudy-Qt_5_11_1-Release

build_script:
  - cd build-MachineStudy-Qt_5_11_1-Release
  - cmake ..\MachineStudy -DCMAKE_BUILD_TYPE=RelWithDebInfo -GNinja -DCMAKE_CXX_COMPILER=cl.exe -DCMAKE_C_COMPILER=cl.exe
  - cmake --build . --target all

after_build:
  - cmake --build . --target install
  - cd install\bin
  - iscc MachineStudy.iss

test: off

artifacts:
  - path: 'src\build-MachineStudy-Qt_5_11_1-Release\install\bin\Output\*.exe'

